---
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: dapr-admin-service-account  
  namespace: {{ .Release.Namespace | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dapr-admin-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dapr-admin-operator-global
subjects:
- kind: ServiceAccount
  name: dapr-admin-service-account
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: dapr-admin-operator
  apiGroup: rbac.authorization.k8s.io