{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-app-admin-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-app-admin-api
  template:
    metadata:
      labels:
        app: dapr-app-admin-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-app-admin-api"
        dapr.io/app-port: "80"
        dapr.io/config: "darp-app-config"
    spec:
      containers:
        - name: dapr-app-admin-api
          image: hub.sample.com/dapr-app-admin-api:0.0.2
          env:
          - name: ASPNETCORE_PATHBASE
            value: "/admin"
          volumeMounts:
            - name: files
              mountPath: /app/appsettings.secret.json
              subPath: admin-api/appsettings.secret.json
            - name: files
              mountPath: /app/App_Data
              subPath: App_Data
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: dapr-admin-pvc
{{- end }}
