{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-app-admin
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-app-admin
  template:
    metadata:
      labels:
        app: dapr-app-admin
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-app-admin"
        dapr.io/app-port: "80"
        dapr.io/config: "darp-app-config"
    spec:
      containers:
        - name: dapr-app-admin
          image: hub.sample.com/dapr-app-admin:0.0.1
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
{{- end }}
