{{- if .Values.admin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-app-sso
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-app-sso
  template:
    metadata:
      labels:
        app: dapr-app-sso
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-app-sso"
        dapr.io/app-port: "80"
        dapr.io/config: "darp-app-config"
    spec:
      containers:
        - name: dapr-app-sso
          image: hub.sample.com/dapr-app-sso:0.0.9
          env:
          - name: ASPNETCORE_PATHBASE
            value: "/sso"
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
{{- end }}
