# Default values for dapr-scaffold.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  storageClass: "dapr-standard-sc"

elasticsearch:
  installOperator: true
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

redisinsight:
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

sqlpad:
  password: ""
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""    

mssql:
  enabled: true
  password: ""
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

admin:
  enabled: true
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

# dependencies:
prometheus:
  alertmanager:
    persistentVolume:
      storageClass: "dapr-standard-sc"

  nodeExporter:
    enabled: false

  server:
    persistentVolume:
      storageClass: "dapr-standard-sc"

  pushgateway:
    persistentVolume:
      storageClass: "dapr-standard-sc"

apisix:
  dataPlane:
    podAnnotations:
      dapr.io/app-id: apisix-gateway
      dapr.io/app-port: "9080"
      dapr.io/enable-metrics: "true"
      dapr.io/enabled: "true"
      dapr.io/metrics-port: "9099"
      dapr.io/sidecar-listen-addresses: 0.0.0.0
      dapr.io/config: ingress-apisix-config

  dashboard:
    enabled: true
    service:
      type: ClusterIP
 
minio:
  replicas: 4      
  persistence:
    storageClass: "dapr-standard-sc"
    size: 16Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"