apiVersion: v1
kind: Service
metadata:
  name: mcs-frontend-samples-clusterip
  namespace: default
spec:
  selector:
    app: mcs-frontend-samples
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
