# Default values for dapr-scaffold.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  storageClass: "dapr-standard-sc"

elasticsearch:
  installOperator: true
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

redisinsight:
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

mssql:
  enabled: true
  password: ""
  persistentVolume:
    storageSize: 8Gi
    storageClass: ""

# dependencies:
eck-operator:
  installCRDs: false

prometheus:
  alertmanager:
    persistentVolume:
      storageClass: "dapr-standard-sc"

  nodeExporter:
    enabled: false

  server:
    persistentVolume:
      storageClass: "dapr-standard-sc"

  pushgateway:
    persistentVolume:
      storageClass: "dapr-standard-sc"

apisix:
  podAnnotations:
    dapr.io/app-id: apisix-gateway
    dapr.io/app-port: "9080"
    dapr.io/enable-metrics: "true"
    dapr.io/enabled: "true"
    dapr.io/metrics-port: "9099"
    dapr.io/sidecar-listen-addresses: 0.0.0.0
    dapr.io/config: ingress-apisix-config

  gateway:
    type: ClusterIP

  ingress-controller:
    enabled: true

  dashboard:
    enabled: true
    service:
            type: ClusterIP
 
  dataPlane:
    service:
      type: ClusterIP
      
