apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: {{ print "dapr-app-redis-master." .Release.Namespace ".svc:6379" }}
    - name: redisPassword
      secretKeyRef:
        name: dapr-redis
        key: redis-password
