apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dapr-grafana
  name: dapr-grafana
spec:
  selector:
    matchLabels:
      app: dapr-grafana
  template:
    metadata:
      labels:
        app: dapr-grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: dapr-grafana
          image: grafana/grafana:10.1.0-ubuntu
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /etc/grafana
              name: ge-config
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: dapr-grafana-pvc
        - name: ge-config
          configMap:
            name: dapr-grafana-config