apiVersion: v1
kind: ConfigMap
metadata:
  name: dapr-grafana-config
data:
    grafana.ini: |
      [server]
      root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
      serve_from_sub_path = true

