apiVersion: v1
kind: Service
metadata:
  name: dapr-grafana-clusterip
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: dapr-grafana
  sessionAffinity: None
  type: ClusterIP