apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: dapr-logs-kibana
  namespace: {{ .Release.Namespace | quote }}
spec:
  version: 7.17.10
  count: 1
  elasticsearchRef:
    name: dapr-logs
    namespace: {{ .Release.Namespace | quote }}
  config:
    xpack.fleet.agents.elasticsearch.hosts:
      {{list (print "http://dapr-logs-es-http." .Release.Namespace ".svc:9200")}}
    xpack.fleet.agents.fleet_server.hosts:
      {{list (print "http://dapr-logs-es-http." .Release.Namespace ".svc:8220")}}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
