{{- if .Values.mssql.enabled }}
{{- $rootPassword := include "common.secrets.passwords.manage" (dict "secret" "dapr-sqlpad-secret" "key" "SQLPAD_ADMIN_PASSWORD" "length" 10 "providedValues" (list "sqlpad.password") "context" $) | trimAll "\"" | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: dapr-sqlpad-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  SQLPAD_ADMIN_PASSWORD: {{ print $rootPassword | b64enc | quote }}
{{- end }}
