apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-pvc