---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvc
  namespace: default
spec:
  storageClassName: "dapr-standard-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
