apiVersion: v1
kind: Service
metadata:
  name: registry-clusterip
  namespace: default
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: tcpsql
