{{- if .Values.mssql.enabled }}
{{- $rootPassword := include "common.secrets.passwords.manage" (dict "secret" "dapr-mssql-secret" "key" "MSSQL_SA_PASSWORD" "length" 10 "providedValues" (list "mssql.password") "context" $) | trimAll "\"" | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: dapr-mssql-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  MSSQL_SA_PASSWORD: {{ print $rootPassword | b64enc | quote }}
{{- end }}
