apiVersion: v1
kind: Service
metadata:
  name: dapr-redisinsight-clusterip
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: dapr-redisinsight
spec:
  selector:
    app: dapr-redisinsight
  ports:
    - name: web
      protocol: TCP
      port: 8001
      targetPort: 8001
