---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-redisinsight
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: dapr-redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-redisinsight
  template:
    metadata:
      labels:
        app: dapr-redisinsight
    spec:
      containers:
        - name: dapr-redisinsight
          image: redislabs/redisinsight:1.9.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: db
              mountPath: /db
          ports:
            - containerPort: 8001
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: dapr-redisinsight-pvc
